Repository fastcampus-febe/TeamB-BE, pull requests merged in 2023-01, with the labels that each got.

#2 Feature/#1 start springboot : Spring Boot 프로젝트 생성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/teamb/travel/TeamBBeApplication.java
  src/main/resources/application.properties
  src/test/java/com/teamb/travel/TeamBBeApplicationTests.java
Labels: enhancement

#4 Feature/#3 project structure : 프로젝트 구조 잡기
  build.gradle
  src/main/java/com/teamb/travel/admin/controller/AdminPageController.java
  src/main/java/com/teamb/travel/aop/LogAdvice.java
  src/main/java/com/teamb/travel/api/BoxOfficeApi.java
  src/main/java/com/teamb/travel/config/SwaggerConfig.java
  src/main/java/com/teamb/travel/controller/ExampleController.java
  src/main/java/com/teamb/travel/dto/ExampleReqDTO.java
  src/main/java/com/teamb/travel/dto/ExampleResDTO.java
  src/main/java/com/teamb/travel/entity/Example.java
  src/main/java/com/teamb/travel/page/controller/PageController.java
  src/main/java/com/teamb/travel/repository/ExampleRepository.java
  src/main/java/com/teamb/travel/service/ExampleService.java
  src/main/java/com/teamb/travel/util/Pagination.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/main/resources/sql/member.sql
Labels: enhancement

#6 #5 - Project에 공유 DB 연결
  src/main/resources/application.properties
Labels: enhancement

#8 Feature/#7 document : Document 6개 추가
  document/API Documentation.txt
  document/TeamB-BE Info.txt
  document/TeamB-BE Notice.txt
  document/TeamB-BE Rule.txt
  document/TeamB-BE Schedule.txt
  document/TeamB-BE Travel Project.txt
Labels: documentation

#9 Develop -> main : 프로젝트 구조 완성하여 main으로 push
  .gitignore
  build.gradle
  document/API Documentation.txt
  document/TeamB-BE Info.txt
  document/TeamB-BE Notice.txt
  document/TeamB-BE Rule.txt
  document/TeamB-BE Schedule.txt
  document/TeamB-BE Travel Project.txt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/teamb/travel/TeamBBeApplication.java
  src/main/java/com/teamb/travel/admin/controller/AdminPageController.java
  src/main/java/com/teamb/travel/aop/LogAdvice.java
  src/main/java/com/teamb/travel/api/BoxOfficeApi.java
  src/main/java/com/teamb/travel/config/SwaggerConfig.java
  src/main/java/com/teamb/travel/controller/ExampleController.java
  src/main/java/com/teamb/travel/dto/ExampleReqDTO.java
  src/main/java/com/teamb/travel/dto/ExampleResDTO.java
  src/main/java/com/teamb/travel/entity/Example.java
  src/main/java/com/teamb/travel/page/controller/PageController.java
  src/main/java/com/teamb/travel/repository/ExampleRepository.java
  src/main/java/com/teamb/travel/service/ExampleService.java
  src/main/java/com/teamb/travel/util/Pagination.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/main/resources/sql/member.sql
  src/test/java/com/teamb/travel/TeamBBeApplicationTests.java
Labels: documentation

#10 #7 - 백엔드 일정 세분화
  document/TeamB-BE Schedule.txt
Labels: documentation

#30 Feature/#28 entity fix
  src/main/java/com/teamb/travel/entity/IsIndoor.java
  src/main/java/com/teamb/travel/entity/Place.java
  src/main/java/com/teamb/travel/entity/PlaceDetail.java
  src/main/java/com/teamb/travel/entity/Reply.java
Labels: bug
