Repository fastcampus-febe/TeamB-BE, pull requests merged in 2023-02, with the labels that each got.

#33 Entity 수정 완
  src/main/java/com/teamb/travel/entity/IsIndoor.java
  src/main/java/com/teamb/travel/entity/Place.java
  src/main/java/com/teamb/travel/entity/PlaceDetail.java
  src/main/java/com/teamb/travel/entity/Reply.java
Labels: bug

#34 #13 - 지역기반 관광지 리스트 조회
  src/main/java/com/teamb/travel/controller/TourListController.java
  src/main/java/com/teamb/travel/dto/PlaceByLocationResDto.java
  src/main/java/com/teamb/travel/repository/IsIndoorRepository.java
  src/main/java/com/teamb/travel/repository/PlaceDetailRepository.java
  src/main/java/com/teamb/travel/repository/PlaceRepository.java
  src/main/java/com/teamb/travel/repository/ReplyRepository.java
  src/main/java/com/teamb/travel/service/PlaceService.java
Labels: enhancement

#36 #35 - 태그 기반 관광지 조회
  src/main/java/com/teamb/travel/controller/TourListController.java
  src/main/java/com/teamb/travel/dto/PlaceByTagResDto.java
  src/main/java/com/teamb/travel/repository/PlaceRepository.java
  src/main/java/com/teamb/travel/service/PlaceService.java
Labels: enhancement

#37 #14 - [GET] 관광지 리스트 조회 (관광지명 조회)
  document/TeamB-BE Rule.txt
  src/main/java/com/teamb/travel/config/PageableConfig.java
  src/main/java/com/teamb/travel/config/SwaggerConfig.java
  src/main/java/com/teamb/travel/controller/PlaceListController.java
  src/main/java/com/teamb/travel/dto/PlaceListReqDTO.java
  src/main/java/com/teamb/travel/dto/PlaceListResDTO.java
  src/main/java/com/teamb/travel/entity/IsIndoor.java
  src/main/java/com/teamb/travel/entity/Place.java
  src/main/java/com/teamb/travel/entity/PlaceDetail.java
  src/main/java/com/teamb/travel/entity/Reply.java
  src/main/java/com/teamb/travel/repository/PlaceDetailRepository.java
  src/main/java/com/teamb/travel/repository/PlaceRepository.java
  src/main/java/com/teamb/travel/repository/ReplyRepository.java
  src/main/java/com/teamb/travel/service/PlaceListService.java
  src/main/resources/logback-spring.xml
Labels: enhancement

#39 Feature/#38 place list refactoring - 관광지 목록 리팩토링 (중복코드 제거, 하나로 통일)
  src/main/java/com/teamb/travel/config/PageableConfig.java
  src/main/java/com/teamb/travel/controller/PlaceListController.java
  src/main/java/com/teamb/travel/controller/TourListController.java
  src/main/java/com/teamb/travel/dto/PlaceByLocationResDto.java
  src/main/java/com/teamb/travel/dto/PlaceByTagResDto.java
  src/main/java/com/teamb/travel/dto/PlaceListResDTO.java
  src/main/java/com/teamb/travel/service/PlaceListService.java
  src/main/java/com/teamb/travel/service/PlaceService.java
Labels: enhancement

#40 #17 - 중기(4~10일) 날씨 조회
  src/main/java/com/teamb/travel/controller/WeatherController.java
  src/main/java/com/teamb/travel/dto/MapReqDto.java
  src/main/java/com/teamb/travel/dto/WeatherLastResDto.java
  src/main/java/com/teamb/travel/dto/WeatherMiddleResDto.java
  src/main/java/com/teamb/travel/dto/WeatherResDto.java
  src/main/java/com/teamb/travel/service/PlaceDetailService.java
Labels: enhancement

#41 Feature/#21 reply update button - [POST] 리뷰 - 관광지 상세페이지 내 리뷰 수정 버튼
  src/main/java/com/teamb/travel/controller/ReplyController.java
  src/main/java/com/teamb/travel/dto/ReplyUpdateReqDTO.java
  src/main/java/com/teamb/travel/dto/ReplyUpdateResDTO.java
  src/main/java/com/teamb/travel/repository/ReplyRepository.java
  src/main/java/com/teamb/travel/service/PlaceListService.java
  src/main/java/com/teamb/travel/service/ReplyService.java
Labels: enhancement

#42 #20 - 리뷰 수정, 삭제 시 본인 확인을 위한 API
  src/main/java/com/teamb/travel/controller/ReplyController.java
  src/main/java/com/teamb/travel/dto/ReplyCheckReqDto.java
  src/main/java/com/teamb/travel/repository/ReplyRepository.java
  src/main/java/com/teamb/travel/service/ReplyService.java
Labels: enhancement

#43 #16 - 단기 날씨 개발 (개발중, 추후 수정(추가) 예정)
  src/main/java/com/teamb/travel/controller/WeatherController.java
  src/main/java/com/teamb/travel/dto/MapReqDTO.java
  src/main/java/com/teamb/travel/dto/WeatherLastResDTO.java
  src/main/java/com/teamb/travel/dto/WeatherResDTO.java
  src/main/java/com/teamb/travel/dto/WeatherResDto.java
  src/main/java/com/teamb/travel/dto/WeatherShortMiddleResDTO.java
  src/main/java/com/teamb/travel/service/WeatherService.java
Labels: enhancement

#44 #12 "관광지 리스트 조회"
  src/main/java/com/teamb/travel/controller/PlaceListController.java
  src/main/java/com/teamb/travel/service/PlaceListService.java
Labels: enhancement

#45 Feature/#16 weather short finish - 단기 날씨 조회 개발 완료
  src/main/java/com/teamb/travel/controller/WeatherController.java
  src/main/java/com/teamb/travel/service/WeatherService.java
Labels: enhancement

#46 #25 - API 명세서 추가
  document/API Documentation.txt
Labels: documentation

#49 Feature/#48 controller refactoring - Controller 반환타입 Result로 변경
  src/main/java/com/teamb/travel/controller/PlaceListController.java
  src/main/java/com/teamb/travel/controller/ReplyController.java
  src/main/java/com/teamb/travel/controller/WeatherController.java
  src/main/java/com/teamb/travel/repository/PlaceRepository.java
Labels: enhancement

#56 #15 "[GET] 관광지 상세페이지 조회"
  src/main/java/com/teamb/travel/controller/PlaceDetailController.java
  src/main/java/com/teamb/travel/dto/PlaceDetailResDTO.java
  src/main/java/com/teamb/travel/dto/detailMaker/EtcMaker.java
  src/main/java/com/teamb/travel/dto/detailMaker/PlaceDetailMaker.java
  src/main/java/com/teamb/travel/dto/detailMaker/PlaceMaker.java
  src/main/java/com/teamb/travel/entity/PlaceDetail.java
  src/main/java/com/teamb/travel/entity/Reply.java
  src/main/java/com/teamb/travel/repository/IsIndoorRepository.java
  src/main/java/com/teamb/travel/repository/PlaceDetailRepository.java
  src/main/java/com/teamb/travel/repository/PlaceRepository.java
  src/main/java/com/teamb/travel/repository/ReplyRepository.java
  src/main/java/com/teamb/travel/service/PlaceDetailService.java
  src/main/java/com/teamb/travel/service/PlaceListService.java
Labels: enhancement

#57 #18 "[GET] 관광지 상세페이지 내 리뷰 출력"
  src/main/java/com/teamb/travel/controller/ReplyController.java
  src/main/java/com/teamb/travel/dto/ReplyListDTO.java
  src/main/java/com/teamb/travel/repository/ReplyRepository.java
  src/main/java/com/teamb/travel/service/ReplyService.java
Labels: enhancement

#60 #23 [DEL] 리뷰 - 관광지 상세페이지 내 리뷰 삭제
  src/main/java/com/teamb/travel/controller/ReplyController.java
  src/main/java/com/teamb/travel/service/ReplyService.java
Labels: enhancement

#62 프로젝트 개발 1차 완료되어 develop ->main으로 PUSH
  build.gradle
  document/API Documentation.txt
  document/TeamB-BE Rule.txt
  document/TeamB-BE Schedule.txt
  src/main/java/com/teamb/travel/api/DetailPlaceApi.java
  src/main/java/com/teamb/travel/api/PlaceApi.java
  src/main/java/com/teamb/travel/config/PageableConfig.java
  src/main/java/com/teamb/travel/config/SwaggerConfig.java
  src/main/java/com/teamb/travel/controller/PlaceDetailController.java
  src/main/java/com/teamb/travel/controller/PlaceListController.java
  src/main/java/com/teamb/travel/controller/ReplyController.java
  src/main/java/com/teamb/travel/controller/WeatherController.java
  src/main/java/com/teamb/travel/dto/MapReqDTO.java
  src/main/java/com/teamb/travel/dto/PlaceDetailResDTO.java
  src/main/java/com/teamb/travel/dto/PlaceListReqDTO.java
  src/main/java/com/teamb/travel/dto/PlaceListResDTO.java
  src/main/java/com/teamb/travel/dto/ReplyCheckReqDto.java
  src/main/java/com/teamb/travel/dto/ReplyListDTO.java
  src/main/java/com/teamb/travel/dto/ReplyModifiedReqDTO.java
  src/main/java/com/teamb/travel/dto/ReplyRequestDTO.java
  src/main/java/com/teamb/travel/dto/ReplyUpdateReqDTO.java
  src/main/java/com/teamb/travel/dto/ReplyUpdateResDTO.java
  src/main/java/com/teamb/travel/dto/WeatherLastResDTO.java
  src/main/java/com/teamb/travel/dto/WeatherResDTO.java
  src/main/java/com/teamb/travel/dto/WeatherShortMiddleResDTO.java
  src/main/java/com/teamb/travel/dto/detailMaker/EtcMaker.java
  src/main/java/com/teamb/travel/dto/detailMaker/PlaceDetailMaker.java
  src/main/java/com/teamb/travel/dto/detailMaker/PlaceMaker.java
  src/main/java/com/teamb/travel/entity/IsIndoor.java
  src/main/java/com/teamb/travel/entity/Place.java
  src/main/java/com/teamb/travel/entity/PlaceDetail.java
  src/main/java/com/teamb/travel/entity/Reply.java
  src/main/java/com/teamb/travel/page/controller/PlaceController.java
  src/main/java/com/teamb/travel/repository/IsIndoorRepository.java
  src/main/java/com/teamb/travel/repository/PlaceDetailRepository.java
  src/main/java/com/teamb/travel/repository/PlaceRepository.java
  src/main/java/com/teamb/travel/repository/ReplyRepository.java
  src/main/java/com/teamb/travel/service/PlaceDetailService.java
  src/main/java/com/teamb/travel/service/PlaceListService.java
  src/main/java/com/teamb/travel/service/ReplyService.java
  src/main/java/com/teamb/travel/service/WeatherService.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: documentation, enhancement

#65 #64 - 생성자 주입으로 변경, 불필요한 import문/주석/접근제어자 삭제
  src/main/java/com/teamb/travel/api/PlaceDetailApi.java
  src/main/java/com/teamb/travel/api/weather/MiddleLastWeatherDetailApi.java
  src/main/java/com/teamb/travel/api/weather/ShortWeatherApi.java
  src/main/java/com/teamb/travel/api/weather/TempApi.java
  src/main/java/com/teamb/travel/controller/PlaceListController.java
  src/main/java/com/teamb/travel/controller/ReplyController.java
  src/main/java/com/teamb/travel/dto/place/detailMaker/EtcMaker.java
  src/main/java/com/teamb/travel/dto/reply/ReplyUpdateReqDTO.java
  src/main/java/com/teamb/travel/dto/reply/ReplyUpdateResDTO.java
  src/main/java/com/teamb/travel/repository/PlaceDetailRepository.java
  src/main/java/com/teamb/travel/repository/PlaceRepository.java
  src/main/java/com/teamb/travel/repository/ReplyRepository.java
  src/main/java/com/teamb/travel/service/PlaceListService.java
Labels: refactoring

#81 #68 - PlaceApi 1차 리팩토링 완료
  src/main/java/com/teamb/travel/api/DataType.java
  src/main/java/com/teamb/travel/api/PlaceApi.java
  src/main/java/com/teamb/travel/api/UrlBuilderToJSONArray.java
  src/main/java/com/teamb/travel/api/weather/MiddleLastWeatherDetailApi.java
  src/main/java/com/teamb/travel/api/weather/ShortWeatherApi.java
  src/main/java/com/teamb/travel/api/weather/TempApi.java
Labels: refactoring

#82 #71 - 민감정보(DB, ID, password, 개인키) 분리
  .gitignore
  src/main/java/com/teamb/travel/api/PlaceApi.java
  src/main/java/com/teamb/travel/api/PlaceDetailApi.java
  src/main/java/com/teamb/travel/api/weather/MiddleLastWeatherDetailApi.java
  src/main/java/com/teamb/travel/api/weather/ShortWeatherApi.java
  src/main/java/com/teamb/travel/api/weather/TempApi.java
  src/main/resources/application.properties
Labels: enhancement

#83 #68 - api 호출하는 부분과 DB에 저장하는 부분을 분리 (PlaceApi)
  src/main/java/com/teamb/travel/api/PlaceApi.java
  src/main/java/com/teamb/travel/service/PlaceApiService.java
Labels: refactoring

#84 #70 [refactoring] 관광지 리스트 조회 시 id 오름차순으로 정렬될 수 있게 수정 (OrderByIdAsc)
  src/main/java/com/teamb/travel/controller/PlaceListController.java
  src/main/java/com/teamb/travel/repository/PlaceRepository.java
  src/main/java/com/teamb/travel/service/PlaceListService.java
Labels: enhancement

#89 #69 - PlaceDetailApi 리팩토링 : api 호출하는 부분과 DB에 저장하는 부분을 분리
  src/main/java/com/teamb/travel/api/PlaceApi.java
  src/main/java/com/teamb/travel/api/PlaceDetailApi.java
  src/main/java/com/teamb/travel/api/UrlBuilderToJSONArray.java
  src/main/java/com/teamb/travel/api/weather/MiddleLastWeatherDetailApi.java
  src/main/java/com/teamb/travel/api/weather/ShortWeatherApi.java
  src/main/java/com/teamb/travel/api/weather/TempApi.java
  src/main/java/com/teamb/travel/service/PlaceApiService.java
  src/main/java/com/teamb/travel/service/PlaceDetailApiService.java
Labels: refactoring

#90 #73 Swagger 설정 추가 및 Swagger 셋팅
  src/main/java/com/teamb/travel/config/SwaggerConfig.java
  src/main/java/com/teamb/travel/controller/PlaceDetailController.java
  src/main/java/com/teamb/travel/controller/PlaceListController.java
  src/main/java/com/teamb/travel/controller/ReplyController.java
Labels: documentation

#93 #73 - SwaggerConfig 주석 처리 (추후 리팩토링 예정)
  src/main/java/com/teamb/travel/config/SwaggerConfig.java
Labels: refactoring

#94 #66 - 날씨 중기 API 관련 리팩토링
  src/main/java/com/teamb/travel/api/weather/MiddleLastWeatherDetailApi.java
  src/main/java/com/teamb/travel/api/weather/TempApi.java
  src/main/java/com/teamb/travel/service/weather/LastWeatherService.java
  src/main/java/com/teamb/travel/service/weather/MiddleWeatherService.java
Labels: bug

#96 #95 [BUGFIX] tourlist 페이징시 17개 이상 안되는 버그 수정
  src/main/java/com/teamb/travel/dto/place/detailMaker/EtcMaker.java
  src/main/java/com/teamb/travel/repository/IsIndoorRepository.java
  src/main/java/com/teamb/travel/service/PlaceDetailService.java
  src/main/java/com/teamb/travel/service/PlaceListService.java
Labels: bug

#97 #73 - SwaggerConfig 관련 Bug 해결
  src/main/java/com/teamb/travel/config/SwaggerConfig.java
Labels: bug

#98 #74 - Controller에 Swagger 설정(설명) 추가
  src/main/java/com/teamb/travel/controller/PlaceListController.java
  src/main/java/com/teamb/travel/controller/ReplyController.java
Labels: documentation

#99 #74 - 스웨거(API 설명) 추가
  src/main/java/com/teamb/travel/controller/ReplyController.java
  src/main/java/com/teamb/travel/controller/WeatherController.java
Labels: documentation

#100 #76 - API Https 처리
  .gitignore
  src/main/java/com/teamb/travel/TeamBBeApplication.java
Labels: enhancement

#102 #101 [REFACTOR] DTO 수정
  src/main/java/com/teamb/travel/controller/ReplyController.java
  src/main/java/com/teamb/travel/dto/reply/ReplyRequestDTO.java
Labels: documentation, refactoring

#103 #79 - @SpringBootTest 어노테이션 주석 처리
  src/test/java/com/teamb/travel/TeamBBeApplicationTests.java
Labels: enhancement

#105 #104 - Http To Https
  src/main/java/com/teamb/travel/TeamBBeApplication.java
Labels: enhancement

#107 #75 - README.md 수정
  README.md
Labels: documentation

#108 REAMDME.md 수정되어 main 으로 PUSH
  README.md
Labels: documentation

#109 #79 - 배포 전 build.gradle에서 안쓰는 의존성 삭제
  build.gradle
  src/main/java/com/teamb/travel/config/SwaggerConfig.java
Labels: refactoring

#110 #79 - 배포 전 build.gradle에서 안쓰는 의존성 삭제 (develop->main)
  build.gradle
  src/main/java/com/teamb/travel/config/SwaggerConfig.java
Labels: refactoring

#111 #79 - 협업 시 발생하는 CORS 문제 해결
  .gitignore
  src/main/java/com/teamb/travel/config/WebConfig.java
Labels: bug, enhancement
